version: '2.0'
services:
  influx-db:
    image: influxdb:1.8-alpine
    volumes:
      - ./container_data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086" 
  grafana:
    image: grafana/grafana:7.1.1
    volumes:
      - ./container_data/grafana:/var/lib/grafana 
      - ./grafana/provisioning:/etc/grafana/provisioning/
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
    ports:
      - "3000:3000"
